# Generated by Django 5.1.1 on 2024-09-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='course',
        ),
    ]
