# Generated by Django 5.1.1 on 2024-10-03 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_options_alter_course_options_and_more'),
        ('payments', '0003_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '장바구니'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at'], 'verbose_name': '장바구니 상품', 'verbose_name_plural': '장바구니 상품들'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='코스'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='payments.cart', verbose_name='장바구니'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='curriculum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum', verbose_name='커리큘럼'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='코드')),
                ('discount_type', models.CharField(choices=[('fixed', '고정 금액 할인'), ('percentage', '정률 할인')], max_length=10, verbose_name='할인 유형')),
                ('discount_value', models.PositiveIntegerField(verbose_name='할인 가치')),
                ('expiration_date', models.DateTimeField(verbose_name='만료일')),
                ('applicable_type', models.CharField(choices=[('curriculum', '커리큘럼'), ('course', '코스')], default='curriculum', max_length=10, verbose_name='적용 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='코스')),
                ('curriculum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum', verbose_name='커리큘럼')),
            ],
            options={
                'verbose_name': '쿠폰',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('canceled', '취소됨')], default='pending', max_length=10, verbose_name='주문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='코스')),
                ('curriculum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum', verbose_name='커리큘럼')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payments.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='국가')),
                ('main_address', models.CharField(help_text='도로명 주소 또는 지번 주소를 입력하세요.', max_length=255, verbose_name='주소')),
                ('detail_address', models.CharField(help_text='아파트 동/호수, 건물 이름과 호수를 입력하세요.(선택 사항)', max_length=255, verbose_name='상세 주소')),
                ('postal_code', models.CharField(max_length=50, verbose_name='우편번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 청구 주소',
            },
        ),
        migrations.CreateModel(
            name='UserBillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', '신용카드'), ('kakaopay', '카카오페이'), ('bank_transfer', '계좌 이체')], max_length=20, verbose_name='결제 방식')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe 고객 ID')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe 결제 방법 ID')),
                ('kakaopay_tid', models.CharField(blank=True, max_length=100, null=True, verbose_name='KakaoPay 거래 ID')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='계좌 번호')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='은행 이름')),
                ('bank_transfer_status', models.CharField(choices=[('pending', '대기 중'), ('completed', '완료')], default='pending', max_length=20, verbose_name='계좌 이체 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('billing_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='payments.userbillingaddress', verbose_name='청구 주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 청구 정보',
                'verbose_name_plural': '사용자 청구 정보들',
                'db_table': 'user_billing_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='payments.order', verbose_name='주문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 구매 내역',
            },
        ),
    ]
