# Generated by Django 5.1.1 on 2024-10-04 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_cart_options_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '주문', 'verbose_name_plural': '주문들'},
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('canceled', '취소됨')], default='pending', max_length=10, verbose_name='결제 상태')),
                ('payment_method', models.CharField(choices=[('credit_card', '신용카드'), ('kakaopay', '카카오페이'), ('bank_transfer', '계좌 이체')], default='credit_card', max_length=20, verbose_name='결제 방식')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='주문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '결제',
            },
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
