# Generated by Django 5.1.1 on 2024-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_order_options_alter_order_user_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchasehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userpurchasehistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '결제', 'verbose_name_plural': '결제들'},
        ),
        migrations.AlterModelOptions(
            name='userbillingaddress',
            options={'verbose_name': '사용자 청구 주소', 'verbose_name_plural': '사용자 청구 주소들'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='만료일'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='환불일'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결제일'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='환불일'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='거래 ID'),
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본 주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('canceled', '취소됨'), ('refunded', '환불됨')], default='pending', max_length=10, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('failed', '실패됨'), ('refunded', '환불됨')], default='pending', max_length=10, verbose_name='결제 상태'),
        ),
        migrations.DeleteModel(
            name='UserBillingInfo',
        ),
        migrations.DeleteModel(
            name='UserPurchaseHistory',
        ),
    ]
