# Generated by Django 5.1.1 on 2024-10-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_options_alter_course_options_and_more'),
        ('payments', '0005_alter_order_options_alter_order_user_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchasehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userpurchasehistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='userbillingaddress',
            options={'verbose_name': '사용자 청구 주소', 'verbose_name_plural': '사용자 청구 주소들'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='만료일'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결제 일시'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='거래 ID'),
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본 주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('refunded', '환불됨')], default='pending', max_length=10, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='코스'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='curriculum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.curriculum', verbose_name='커리큘럼'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('refunded', '환불됨')], default='pending', max_length=10, verbose_name='결제 상태'),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='detail_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='상세 주소'),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='main_address',
            field=models.CharField(max_length=255, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='userbillingaddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='우편번호'),
        ),
        migrations.DeleteModel(
            name='UserBillingInfo',
        ),
        migrations.DeleteModel(
            name='UserPurchaseHistory',
        ),
    ]
