# Generated by Django 5.1.1 on 2024-10-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_userpurchasehistory_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '결제', 'verbose_name_plural': '결제들'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.userbillingaddress', verbose_name='청구 주소'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='취소 일시'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fail_reason',
            field=models.TextField(blank=True, null=True, verbose_name='실패 사유'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('failed', '실패함'), ('cancelled', '취소됨')], default='pending', max_length=10, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('failed', '실패함'), ('cancelled', '취소됨')], default='pending', max_length=10, verbose_name='결제 상태'),
        ),
    ]
