# Generated by Django 5.1.1 on 2024-10-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_options_alter_course_options_and_more'),
        ('payments', '0007_alter_payment_options_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='코스'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum', verbose_name='커리큘럼'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='코스'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.curriculum', verbose_name='커리큘럼'),
        ),
    ]
