# Generated by Django 5.1.1 on 2024-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_cartitem_course_alter_cartitem_curriculum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': '결제', 'verbose_name_plural': '결제들'},
        ),
        migrations.AlterModelOptions(
            name='userbillingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': '사용자 청구 주소', 'verbose_name_plural': '사용자 청구 주소들'},
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
