# Generated by Django 5.1.1 on 2024-10-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_billing_address_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('failed', '실패함'), ('cancelled', '취소됨'), ('refunded', '환불됨')], default='pending', max_length=10, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('failed', '실패함'), ('cancelled', '취소됨'), ('refunded', '환불됨')], default='pending', max_length=10, verbose_name='결제 상태'),
        ),
    ]
