# Generated by Django 5.1.1 on 2024-10-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_metadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': '장바구니', 'verbose_name_plural': '장바구니들'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fail_reason',
        ),
    ]
