# Generated by Django 5.1.1 on 2024-10-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_cart_options_remove_payment_fail_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': '장바구니', 'verbose_name_plural': '장바구니 목록'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '주문', 'verbose_name_plural': '주문 목록'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': '결제', 'verbose_name_plural': '결제 목록'},
        ),
        migrations.AlterModelOptions(
            name='userbillingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': '사용자 청구 주소', 'verbose_name_plural': '사용자 청구 주소 목록'},
        ),
    ]
