version: '3.8'

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@postgresql:5432/postgres
    depends_on:
      - postgresql
      - redis

  celery_worker:
    build: .
    command: celery -A weaverse-backend worker -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@postgresql:5432/postgres
    depends_on:
      - web
      - redis
      - postgresql

  celery_beat:
    build: .
    command: celery -A weaverse-backend beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@postgresql:5432/postgres
    depends_on:
      - web
      - redis
      - postgresql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data: