# Generated by Django 5.1.1 on 2024-10-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwtauth", "0003_socialaccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialAccount",
        ),
    ]
