# Generated by Django 5.1.1 on 2024-10-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_options_alter_course_options_and_more'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='topic',
        ),
        migrations.AddField(
            model_name='image',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.topic'),
        ),
    ]
