# Generated by Django 5.1.1 on 2024-10-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_options_alter_course_options_and_more'),
        ('materials', '0002_image_video_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.topic'),
        ),
    ]
