# Generated by Django 5.1.1 on 2024-10-13 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_topic_description'),
        ('materials', '0003_image_image_image_user_alter_image_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='', verbose_name='이미지 파일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.course'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='', verbose_name='비디오 파일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoeventdata',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_event_datas', to=settings.AUTH_USER_MODEL, verbose_name='시청 기록의 해당 사용자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoeventdata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_event_datas', to='materials.video', verbose_name='시청 기록의 해당 비디오'),
        ),
    ]
