# Generated by Django 5.1.1 on 2024-10-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_topic_description'),
        ('materials', '0005_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.topic'),
        ),
    ]
