# Generated by Django 5.1.1 on 2024-10-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_image_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videoeventdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='image',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지 파일'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='비디오 파일'),
        ),
        migrations.AlterField(
            model_name='videoeventdata',
            name='duration',
            field=models.FloatField(verbose_name='동영상 전체 길이'),
        ),
        migrations.AlterField(
            model_name='videoeventdata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_event_datas', to='materials.video', verbose_name='시청 기록의 해당 동영상'),
        ),
    ]
