# Generated by Django 5.1.1 on 2024-10-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_image_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
    ]
