# Generated by Django 5.1.1 on 2024-10-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_remove_image_image_url_remove_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='https://paullab.co.kr/images/weniv-licat.png', verbose_name='이미지 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=bZh8oUIDfdI&t=1s', verbose_name='동영상 URL'),
        ),
    ]
