# Generated by Django 5.1.1 on 2024-10-03 07:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 3, 7, 0, 12, 755621, tzinfo=datetime.timezone.utc), verbose_name='생성 일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(default='', max_length=20, verbose_name='자기소개'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='', max_length=20, verbose_name='닉네임'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='연락처'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': False}, related_name='tutors', related_query_name='tutor', to=settings.AUTH_USER_MODEL, verbose_name='수강 학생들'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신 일자'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
    ]
