# Generated by Django 5.1.1 on 2024-09-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Node.js', 'Node.js'), ('AWS', 'AWS'), ('Docker', 'Docker'), ('DB', 'DB')], default='JavaScript', max_length=255, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='beginner', max_length=255, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='', verbose_name='간단한 설명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='프리미엄 여부'),
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('video', '동영상'), ('article', '글'), ('assignment', '과제'), ('quiz', '퀴즈')], default='video', max_length=255, verbose_name='주제 타입'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(verbose_name='설명'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='문제')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.topic')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='문제')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_question', to='courses.topic')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='선택지')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_question_choices', to='courses.multiplechoicequestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
