# Generated by Django 5.1.1 on 2024-10-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_price_curriculum_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"verbose_name": "과제", "verbose_name_plural": "과제 목록"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "코스",
                "verbose_name_plural": "코스 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculum",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "커리큘럼",
                "verbose_name_plural": "커리큘럼 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="lecture",
            options={
                "ordering": ["order"],
                "verbose_name": "강의",
                "verbose_name_plural": "강의 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="multiplechoicequestion",
            options={
                "verbose_name": "객관식 문제",
                "verbose_name_plural": "객관식 문제 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["order"],
                "verbose_name": "주제",
                "verbose_name_plural": "주제 목록",
            },
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to="courses.topic",
                verbose_name="주제",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="course",
            name="curriculum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.curriculum",
                verbose_name="커리큘럼",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="courses.course",
                verbose_name="코스",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_choice_question",
                to="courses.topic",
                verbose_name="주제",
            ),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestionchoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestionchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_choice_question_choices",
                to="courses.multiplechoicequestion",
                verbose_name="문제",
            ),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestionchoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="courses.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
    ]
