name: Main CD

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.key }}
          script: |
            set -e
            cd /home/ubuntu/weaverse/weaverse-backend/
            git pull origin main

            source venv/bin/activate
            pip install -r requirements.txt

            python manage.py collectstatic --noinput

            sudo systemctl restart weaverse
