name: Dev CI

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: 체크아웃 레포지토리
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: github scrests를 사용하여 환경 변수 복사
        run: |
          echo "SECRET_KEY=${{ secrets.env }}" >> .env
      - name: migrate 실행
        run: |
          python manage.py migrate
      - name: 테스트 실행
        run: |
          python manage.py test
